local LSM = LibStub('LibSharedMedia-3.0')

if LSM == nil then return end

LSM:Register('font','Bui Prototype', [[Interface\AddOns\ElvUI_BenikUI\media\fonts\PROTOTYPE.TTF]])
LSM:Register('font','Bui PrototypeRU', [[Interface\AddOns\ElvUI_BenikUI\media\fonts\PROTOTYPE_RU.TTF]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font','Bui Visitor1', [[Interface\AddOns\ElvUI_BenikUI\media\fonts\visitor1.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font','Bui Visitor2', [[Interface\AddOns\ElvUI_BenikUI\media\fonts\visitor2.ttf]])
LSM:Register('font','Bui Tukui', [[Interface\AddOns\ElvUI_BenikUI\media\fonts\uf_font.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font','Bui Kait', [[Interface\AddOns\ElvUI_BenikUI\media\fonts\heavy_dock_kait.ttf]])
LSM:Register('font','Bui ArialN', [[Interface\AddOns\ElvUI_BenikUI\media\fonts\ARIALN.ttf]])
LSM:Register('font','Bui Homizio', [[Interface\AddOns\ElvUI_BenikUI\media\fonts\homizio_bold.ttf]])
LSM:Register('statusbar','BuiFlat', [[Interface\AddOns\ElvUI_BenikUI\media\textures\Flat.tga]])
LSM:Register('statusbar','BuiOnePixel', [[Interface\AddOns\ElvUI_BenikUI\media\textures\BuiOnePixel.tga]])
LSM:Register('statusbar','BuiMelli', [[Interface\AddOns\ElvUI_BenikUI\media\textures\Melli.tga]])
LSM:Register('statusbar','BuiMelliDark', [[Interface\AddOns\ElvUI_BenikUI\media\textures\MelliDark.tga]])
LSM:Register('statusbar','BuiEmpty', [[Interface\AddOns\ElvUI_BenikUI\media\textures\Empty.tga]])
LSM:Register('statusbar','BuiKait1', [[Interface\AddOns\ElvUI_BenikUI\media\textures\Kait1.tga]])
LSM:Register('statusbar','BuiKait2', [[Interface\AddOns\ElvUI_BenikUI\media\textures\Kait2.tga]])
LSM:Register('statusbar','Bui-pHish1', [[Interface\AddOns\ElvUI_BenikUI\media\textures\pHishTex5.tga]])
LSM:Register('statusbar','Bui-pHish2', [[Interface\AddOns\ElvUI_BenikUI\media\textures\pHishTex29.tga]])
LSM:Register('statusbar','Bui-pHish3-Shadow', [[Interface\AddOns\ElvUI_BenikUI\media\textures\pHishTex35.tga]])
LSM:Register('statusbar','Bui-Kringel-Shadow', [[Interface\AddOns\ElvUI_BenikUI\media\textures\KMT32.tga]])